name: Deploy to GitHub Pages

on:
  push:
    branches: ["**"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare deployment content
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME}
          if [ "$BRANCH_NAME" = "main" ]; then
            DEST=build
          else
            DEST=build/preview/$BRANCH_NAME
            mkdir -p "$DEST"
          fi
          rsync -a --exclude=build ./ "$DEST"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
